services:
  client-frontend:
    image: frontend:latest
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    image: 'backend:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/studench
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'


    ports:
        - '15432:5432'
    volumes:
      - ./backend/src/main/resources/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
